server:
  tomcat:
    url-encoding: UTF-8
  servlet:
    context-path: /
spring:
  application:
    name: edu-spring-data-jdbc
  profiles:
    active: prd
  banner:
    location: "classpath:banner.txt"
# caffein cache 사용을 위해 cache name 설정
  #cache:
  #  cache-names: employee
  cache:
    type: redis
  data:
    redis:
      host: 211.252.87.34 # 127.0.0.1
      port: 30020 # 6379

# R2DBC
#spring.r2dbc.url=r2dbc:mariadb://localhost:3306/spring_test
#spring.r2dbc.username=root
#spring.r2dbc.password=root
#spring.r2dbc.pool.enabled=true
# spring.r2dbc.pool.initial-size=50
# spring.r2dbc.pool.max-size=50
# 재시작시 데이터 유지
#  spring.session.redis.flush-mode=on_save
  # Redis 서버 접속 대기시간 (서버 접속이 어려운 상황을 감안하도록 한다)
#  spring.data.redis.timeout=500ms

#  security:
#    user:
#      name: admin
#      password: admin
#  boot:
#    admin:
#      client:
#        url: http://localhost:8080

# logging
logging:
  config: classpath:log4j2.xml

#jasypt encryptor
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

jwt:
  token-expiration-seconds: 1800
  secret-key: CloudNativeKtEduSecretKey20240228CloudNativeKtEduSecretKey20240228CloudNativeKtEduSecretKey20240228
#  secret-key: ce79e749650fb0c8595801d94c222bbc786ccbcf01d50f09cc579cd8b6143e38e8c2d551e658355a7cd819fe424d8a223ceee652edd38cd74f2e2b5da79dadfb91b93f4b03cdb89d410dbf2c9158f5fe75af7380297bc1682e421a204f813b5454e43f746805bf39120dad0f7e06e179d5dfdcc72f9d40371785691a9c8ab8e088f5f39a68a31c45bc1dadd52e6195dc7de9ddf4fb05232baa9ef2a59fb5e3e6397cdbedae47cdf3db0557fe25124714c23babfef3345dfc93e1c01b843e1f2cac326e8d8c0dbb603de9dd1e5d738463c5e94c9c8f68efa0a10f10f095d8a3768e182ed21706b68d3d35d1c30fc25a3990b7e193e0131aa8246748a2aa982463

# app
app-info:
  app-name: "edu-spring-data-jdbc"
  title: "Cloud Native Edu API"
  build:
    version: '@project.version@'
    timestamp: '@app.build.timestamp@'
  user-id: "jake lee"
  org-id: "KT"
  desc: "EDU 관련 설명입니다."
  doc-url: "https://github.com/kt-cloudnative/education/"
  license: "Apache License"
  license_url: "https://github.com/kt-cloudnative/education/"
  version: "@app.build.timestamp@"
  doc-desc: "교육용"

